version: "3.9"

services:
  # Sidekiq depenedency
  redis:
    image: "redis/redis-stack-server:latest"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    container_name: "redis-amp"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  # Rails dependency
  postgres:
    image: "postgres:10.13"
    container_name: "psql-dev-amp"
    ports:
      - "5441:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - dbdata:/var/lib/postgresql/data

  # Dev environment
  dev:
    image: "dev-lms-amp"
    build:
      context: ./
      dockerfile: ./dockerfile/Dockerfile
      args:
        - GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN}
    volumes:
      - ~/.vim:/root/.vim
      - ~/.vimrc:/root/.vimrc
      - ./:/ruby/src/github.com/dev-lms-poc
    depends_on:
      - postgres
    container_name: "dev-poc-amp"
    ports:
      - "8088:8080"
      - "3000:3000"
      - "9398:9394"
    env_file: .env
    environment:
      - DATABASE_URL=${POSTGRES_URL}
      - DATABASE_MAX_CONNECTION=${DATABASE_MAX_CONNECTION}
      - DATABASE_POOL_TIMEOUT=${DATABASE_POOL_TIMEOUT}
      - TEST_DATABASE_URL=${POSTGRES_URL}
      - REDIS_URL=redis://redis:6379/0
      - BUNDLE_ENTERPRISE__CONTRIBSYS__COM=${BUNDLE_ENTERPRISE__CONTRIBSYS__COM}
      - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}
      - GOOGLE_PUBSUB_VERIFICATION_TOKEN=${GOOGLE_PUBSUB_VERIFICATION_TOKEN}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    tty: true
    stdin_open: true

volumes:
  dbdata:
  redis_data:
    driver: local
