CREATE TYPE "amplifier_status" AS ENUM (
  'draft',
  'published',
  'archived'
);

CREATE TYPE "conversation_type" AS ENUM (
  'question',
  'answer'
);

CREATE TYPE "speaker_type" AS ENUM (
  'ai',
  'human'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "created_at" timestamp,
  "country_code" int
);

CREATE TABLE "amplifiers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "client_id" int,
  "title" text,
  "start_at" datetime,
  "state" amplifier_status,
  "user_id" int,
  "description" text,
  "amplifier_type" int
);

CREATE TABLE "amplifier_conversations" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text,
  "amplifier_id" int,
  "conversation_type" conversation_type
);

CREATE TABLE "messages" (
  "content" string,
  "speaker" speaker_type,
  "amplifier_conversations_id" int
);

CREATE TABLE "amplifier_types" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" string
);

CREATE TABLE "amplifier_prompts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" string,
  "description" text,
  "amplifier_type" int
);

CREATE TABLE "amplifier_prompt_categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" string,
  "prompt" string,
  "amplifier_prompt_id" int
);

CREATE TABLE "attachments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "file_type" string,
  "url" string,
  "amplifier_conversations_id" int
);

CREATE INDEX "amplifier_client" ON "amplifiers" ("client_id");

CREATE UNIQUE INDEX ON "amplifiers" ("id");

ALTER TABLE "amplifiers" ADD FOREIGN KEY ("amplifier_type") REFERENCES "amplifier_types" ("id");

ALTER TABLE "amplifier_conversations" ADD FOREIGN KEY ("amplifier_id") REFERENCES "amplifiers" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("amplifier_conversations_id") REFERENCES "amplifier_conversations" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "amplifiers" ("user_id");

ALTER TABLE "amplifier_prompts" ADD FOREIGN KEY ("amplifier_type") REFERENCES "amplifier_types" ("id");

ALTER TABLE "amplifier_prompt_categories" ADD FOREIGN KEY ("amplifier_prompt_id") REFERENCES "amplifier_prompts" ("id");

ALTER TABLE "attachments" ADD FOREIGN KEY ("amplifier_conversations_id") REFERENCES "amplifier_conversations" ("id");
